version: "3"
services:
    mariadb:
        container_name: "mariadb"
        build: ./requirements/mariadb/
        restart: unless-stopped
        networks:
            - localhost
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - volume-mariadb:/var/lib/mysql/
        init: true
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - volume-wordpress:/var/www/wordpress/
        ports:
            - "443:443"
        networks:
            - localhost
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - "wordpress"
        init: true
    wordpress:
        container_name: "wordpress"
        build: ./requirements/wordpress/
        restart: unless-stopped
        networks:
            - localhost
        ports:
            - "9000:9000"
        depends_on:
            - "mariadb"
        env_file:
            - .env
        volumes:
            - volume-wordpress:/var/www/wordpress/
        init: true
    redis:
        container_name: "redis"
        build: ./requirements/bonus/redis/
        restart: unless-stopped
        networks:
            - localhost
        init: true
    adminer:
        build: ./requirements/bonus/adminer
        container_name: adminer
        image : adminer
        depends_on:
            # - mariadb
            - wordpress
        restart: unless-stopped
        networks:
          - localhost
        # environment:
        #     ADMINER_DEFAULT_SERVER: ll
        volumes:
            - volume-wordpress:/var/www/html/
        init: true
    ftp:
        build: ./requirements/bonus/ftp-server
        container_name: ftp
        image : ftp
        depends_on:
            - wordpress
        restart: unless-stopped
        networks:
          - localhost
        ports:
            - "21:21"
            - "40000-40010:40000-40010"
        volumes:
            - volume-wordpress:/home/ali/wordpress
        init: true
    portainer:
        build: ./requirements/bonus/portainer
        container_name: portainer
        image : portainer
        restart: 'always'
        volumes: 
          - volume-portainer:/data
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - localhost
        init: true
networks:
    localhost:
        driver: bridge
volumes:
    volume-mariadb:
        # driver: local
        # driver_opts:
        #     type: 'none'
        #     o: 'bind'
        #     device: /home/abayar/data/mariadb
    volume-wordpress:
        # driver: local
        # driver_opts:
        #     type: 'none'
        #     o: bind
        #     device: /home/abayar/data/wordpress
    volume-portainer:
        # driver: local
        # driver_opts:
        #   type: none
        #   device: /home/abayar/data/portainer
        #   o: bind
