version: "3"
services:
    mariadb:
        container_name: "mariadb"
        build: ./requirements/mariadb/
        restart: unless-stopped
        networks:
            - localhost
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - volume-mariadb:/var/lib/mysql/
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - volume-wordpress:/var/www/wordpress/
        ports:
            - "443:443"
        networks:
            - localhost
        restart: unless-stopped
        depends_on:
            - "wordpress"
    wordpress:
        container_name: "wordpress"
        build: ./requirements/wordpress/
        restart: unless-stopped
        networks:
            - localhost
        ports:
            - "9000:9000"
        depends_on:
            - "mariadb"
        env_file:
            - .env
        volumes:
            - volume-wordpress:/var/www/wordpress/
networks:
    localhost:
        driver: bridge
volumes:
    volume-mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: ${PWD}/data/mariadb
    volume-wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: ${PWD}/data/wordpress
